[mgr]
marker_copied = { fg = "green", bg = "green" }
marker_cut = { fg = "red", bg = "red" }
marker_marked = { fg = "magenta", bg = "magenta" }
marker_selected = { fg = "yellow", bg = "yellow" }

cwd = { fg = "yellow" }
hovered = { fg = "yellow", bg = "black" }

preview_hovered = { dim = true }

find_keyword = { underline = true, fg = "red" }
find_position = {}

count_copied = { fg = "black", bg = "green" }
count_cut = { fg = "black", bg = "red" }
count_selected = { fg = "black", bg = "yellow" }

border_symbol = "â”‚"
border_style = { fg = "white" }

[tabs]
active   = { fg = "yellow", bg = "black" }
inactive = { fg = "black", bg = "blue" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "#181616", bg = "#7a8e99" }
normal_alt = { fg = "#7a8e99", bg = "#0d0c0c" }
select_main = { fg = "#181616", bg = "#a292a3" }
select_alt = { fg = "#a292a3", bg = "#0d0c0c" }
unset_main = { fg = "#181616", bg = "#c0a574" }
unset_alt = { fg = "#c0a574", bg = "#0d0c0c" }


[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
overall = { fg = "#7fb4ca", bg = "#16161d" }

progress_label = { fg = "#7a8e99", bg = "#0d0c0c", bold = true }
progress_normal = { fg = "#0d0c0c", bg = "#181616" }
progress_error = { fg = "#0d0c0c", bg = "#181616" }

perm_type = { fg = "#8a9a7b" }
perm_read = { fg = "#c0a574" }
perm_write = { fg = "#ff5d62" }
perm_exec = { fg = "#7aa89f" }
perm_sep = { fg = "#a292a3" }

[pick]
border = { fg = "#8ea4a2" }
active = { fg = "#a292a3", bold = true }
inactive = {}

[input]
border = { fg = "#8ea4a2" }
title = {}
value = {}
selected = { reversed = true }

[completion]
border = { fg = "#8ea4a2" }
active = { reversed = true }
inactive = {}

[tasks]
border = { fg = "#8ea4a2" }
title = {}
hovered = { fg = "#a292a3" }

[which]
cols = 2
separator = " - "
separator_style = { fg = "#a6a69c" }
mask = { bg = "#16161d" }
rest = { fg = "#a6a69c" }
cand = { fg = "#7a8e99" }
desc = { fg = "#54546d" }

[help]
on = { fg = "#7aa89f" }
run = { fg = "#7aa89f" }
desc = { fg = "#7aa89f" }
hovered = { reversed = true, bold = true }
footer = { fg = "#181616", bg = "#a4a8a7" }

[notify]
title_info = { fg = "#8a9a7b" }
title_warn = { fg = "#c0a574" }
title_error = { fg = "#ff5d62" }

[filetype]
rules = [
    # broken links
    { name = "*", is = "orphan", fg = "red" },

    # images
    { mime = "image/*", fg = "magenta" },

    # media
    { mime = "{audio,video}/*", fg = "magenta" },

    # archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "red" },

    # executables
    { name = "*", is = "exec", fg = "green" },

    # documents
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "green" },

    # languages
    { name = "*.{c,cpp,h,py,js,ts,java,cs,html,css,md,go,jsx,tsx,sh,kt,lua}", fg = "yellow" },

    # links
    { name = "*", is = "link", fg = "cyan" },

    # directories links
    { name = "*/", is = "link", fg = "cyan" },

    # fallback
    { name = "*", fg = "white" },
    { name = "*/", fg = "blue" },
]
